<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S5FPP8F" name="unittesting.calculator.CalculatorTestSquare" tests="2" failures="0" timestamp="15 May 2018 21:11:52 GMT" time="1.033" errors="1">
  <testcase name="testSquareRoot" time="1.030" classname="unittesting.calculator.CalculatorTestSquare">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testSquareRoot() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testSquareRoot() didn't finish within the time-out 1000
	at unittesting.calculator.Calculator.squareRoot(Calculator.java:27)
	at unittesting.calculator.CalculatorTestSquare.testSquareRoot(CalculatorTestSquare.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testSquareRoot -->
  <testcase name="testSquare" time="0.003" classname="unittesting.calculator.CalculatorTestSquare"/>
</testsuite> <!-- unittesting.calculator.CalculatorTestSquare -->
